---
- name: Download Jenkins war
  get_url: url=http://ftp-chi.osuosl.org/pub/jenkins/war/2.152/jenkins.war dest=/usr/share/tomcat/webapps/jenkins.war mode=0755

- name: Start tomcat
  service: name=tomcat state=restarted enabled=yes
